# -*- coding: utf-8 -*-
"""app

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dqrKuuUEqKIfIw47HnBXcFP3-8qSLxeV
"""

pip install streamlit

import streamlit as st
from pathlib import Path

# ==============================
# CONFIGURATION GÉNÉRALE
# ==============================
st.set_page_config(
    page_title="Application Financière – Planification Stratégique – Mohamed Falilou Fall",
    page_icon="",
    layout="wide",
    initial_sidebar_state="expanded"
)

# ==============================
# INITIALISATION DE L'ÉTAT GLOBAL
# ==============================
def init_session_state():
    if "hypotheses" not in st.session_state:
        st.session_state.hypotheses = {
            "ca": 0.0,
            "croissance": 0.10,
            "prix": 0.0,
            "volume": 0,
            "charges": 0.0,
            "amortissements": 0.0,
            "charges_fixes": 0.0,
            "cout_variable": 0.0,
            "stocks": 0.0,
            "creances": 0.0,
            "dettes": 0.0
        }

    if "scenario" not in st.session_state:
        st.session_state.scenario = "Central"

init_session_state()

# ==============================
# TITRE PRINCIPAL
# ==============================
st.title("Application Financière de Planification Stratégique et Comptable")
st.caption("Business Plan • Trésorerie • Rentabilité • Scénarios • Export")
st.markdown("**Auteur : Mohamed Falilou Fall**")

# ==============================
# SIDEBAR – NAVIGATION
# ==============================
st.sidebar.title("Navigation")

pages = {
    "Hypothèses d’activité": "01_Hypotheses_Activite.py",
    "Compte de résultat": "02_Compte_Resultat_Previsionnel.py",
    "Seuil de rentabilité": "03_Seuil_Rentabilite.py",
    "BFR": "04_BFR.py",
    "Plan de financement": "05_Plan_Financement.py",
    "Plan de trésorerie": "06_Plan_Tresorerie.py",
    "Données financières clés": "07_Donnees_Financieres_Cles.py",
    "Scénarios": "08_Scenarios.py",
    "Export & reporting": "09_Export.py"
}

selection = st.sidebar.radio("Choisir un module", list(pages.keys()))

# ==============================
# RÉSOLUTION DU CHEMIN (CORRIGÉ)
# ==============================
try:
    BASE_DIR = Path(__file__).parent
except NameError:
    # Cas Jupyter / Colab / IPython
    BASE_DIR = Path.cwd()

PAGE_DIR = BASE_DIR / "app" / "pages"
page_file = PAGE_DIR / pages[selection]

# ==============================
# CHARGEMENT DYNAMIQUE DU MODULE
# ==============================
if page_file.exists():
    with open(page_file, "r", encoding="utf-8") as f:
        code = f.read()
        exec(code, globals())
else:
    st.error(f"Module introuvable : {page_file}")

# ==============================
# FOOTER
# ==============================
st.sidebar.markdown("---")
st.sidebar.caption(
    "© Application Financière – Modèle institutionnel\n"
    "Mohamed Falilou Fall – Décembre 2025"
)