# -*- coding: utf-8 -*-
"""Arborescence du projet

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1udB2_lxLEpqXTQXHLNG3o_iaMQ141_k9
"""

Application_Financiere/
│
├── app/
│   ├── main.py                 # Point d’entrée Streamlit
│   ├── pages/
│   │   ├── 01_Hypotheses_Activite.py
│   │       └── # Formulaires de saisie + contrôle des données
│   │       └── # Graphiques de synthèse des hypothèses
│   │       └── # Sliders / input dynamiques pour tuning
│   │
│   │   ├── 02_Compte_Resultat_Previsionnel.py
│   │       └── # DataFrame Pandas pour le calcul
│   │       └── # Graphiques interactifs (Plotly) : CR prévisionnel
│   │       └── # Paramètres ajustables pour scénarios financiers
│   │
│   │   ├── 03_Seuil_Rentabilite.py
│   │       └── # Calcul point mort
│   │       └── # Courbes CA vs Seuil
│   │       └── # Sliders pour tuning marges et prix
│   │
│   │   ├── 04_BFR.py
│   │       └── # Calcul BFR, délais clients/fournisseurs
│   │       └── # Graphiques BFR mensuels
│   │       └── # Sliders pour modifier hypothèses flux
│   │
│   │   ├── 05_Plan_Financement.py
│   │       └── # Tableaux financement
│   │       └── # Graphiques besoins vs ressources
│   │       └── # Tuning : ajustement emprunts, apports
│   │
│   │   ├── 06_Plan_Tresorerie.py
│   │       └── # Cash-flow mensuel
│   │       └── # Courbes trésorerie cumulée (Plotly)
│   │       └── # Ajustements dynamiques pour anticiper déficits
│   │
│   │   ├── 07_Donnees_Financieres_Cles.py
│   │       └── # KPI : EBITDA, VAN, TRI
│   │       └── # Radar charts, cartes KPI
│   │       └── # Sliders pour tester impact hypothèses
│   │
│   │   ├── 08_Scenarios.py
│   │       └── # Gestion multi-scénarios (optimiste / central / pessimiste)
│   │       └── # Tableaux comparatifs interactifs
│   │       └── # Sliders pour sensibilité et tuning
│   │
│   │   ├── 09_Export.py
│   │       └── # Export Excel & PDF
│   │       └── # Résumés graphiques prêts à partager
│
├── data/                                    # Données d’entrée / modèles Excel
│   ├── input.xlsx
│   └── template_cr.xlsx
│
├── utils/                                   # Fonctions utilitaires
│   ├── calculs_financiers.py                # CR, BFR, seuil, cash-flow
│   ├── visualisation.py                     # Graphiques interactifs (Plotly / Matplotlib)
│   └── tuning.py                             # Fonctions de tuning, sliders, scenarios dynamiques
│
├── reports/                                 # Rapports PDF / exports Excel
│
├── requirements.txt                         # Librairies Python (streamlit, pandas, plotly, etc.)
└── README.md                                # Documentation projet

